### ISSUE TITLE
Signout fails after user account has been deleted

### ISSUE THREAD

**Issue by paule89123** [supabase/auth#1518]
## Describe the bug
supabase.auth.signOut() fails if the user has been deleted. The error is `AuthApiError: User from sub claim in JWT does not exist`

## To Reproduce

See code below (under "Additional context")

## Expected behavior

supabase.auth.signOut() should clear the local cache if the user has been deleted.

## System information

- OS: iOS
- Version of supabase-js: 2.25.0
- Version of Node.js: 18.19.0

## Additional context

My app needs to allow users to delete their accounts. In order to do this, I have created a database function that does the following:

`  -- Get the user's ID and email address
  SELECT id, email INTO user_id, user_email FROM auth.users WHERE id = auth.uid();

  -- Insert a record into the deleted_users table
  INSERT INTO public.deleted_users (id, email)
  VALUES (user_id, user_email);

  -- Delete the user from the auth.users table
  DELETE FROM auth.users WHERE id = user_id;`

I call this from the client with:

`await supabase.rpc('delete_user')`

This successfully deletes the user from auth.users, and deletes their session and refresh token from the db as well. However, the user's session is still cached locally on the client (I'm using React Native/Expo). Thus, I need to log the user out locally. However, calling `await supabase.auth.signOut()` fails with the error:

`AuthApiError: User from sub claim in JWT does not exist`

**Comment by hf** [comment]
Closing as it appears to have been addressed.

**Comment by paule89123** [comment]
I've just tested this again after updating to the latest version of @supabase/supabase-js (^2.43.4) and it's still not fixed.

**Comment by Albertbol** [comment]
same here

**Comment by armenavanesi** [comment]
Same issue

**Comment by SamiChab** [comment]
Same for me

**Comment by lenzi-erickson** [comment]
I am having an issue that sounds very similar and opened a new issue: https://github.com/supabase/auth/issues/1801

**Comment by shine-jung** [comment]
I deleted the cookies instead of using await supabase.auth.signOut().

```
const deleteAllCookies = () => {
  const cookies = document.cookie.split(';');

  cookies.forEach((cookie) => {
    const cookieName = cookie.split('=')[0].trim();
    document.cookie = `${cookieName}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/;`;
  });
};
```
