### ISSUE TITLE
Information about Contributing Regional SMS Provider (via Send SMS HTTP Hook)

### ISSUE THREAD

**Issue by J0** [supabase/auth#1582]
# Regional SMS Senders

We're accepting contributions for regional SMS providers via the Send SMS Hook.  

Contributors for select SMS providers (e.g. msg91 (@MeetChaudhari) and Africa's Talking (@mutumbakato) ) can add the following lines to your `config.toml` on the latest version of the CLI to enable the hook locally. If you are interested in contributing a regional provider for a hook which is not msg91 or Africa's Talking please make a comment with the provider name below. 

Note that this feature is only available for use with the CLI locally - it will be available on Supabase projects once we merge [the frontend](https://github.com/supabase/supabase/pull/22495)

```
[auth.hook.send_sms]
enabled = true
uri = "http://host.docker.internal:54321/functions/v1/sms_sender"
secret = "env(SEND_SMS_HOOK_SECRET)"
```

This configuration assumes we're using a Supabase Edge Function which is called `sms_sender` though in practice you can use any HTTP endpoint of your choosing. With respect to the secret, it should take the form `v1,whsec_<standard-base64-string>`. You can use a generic [base64 encoding tool](https://www.base64encode.org/) to help generate the base64 string.

You can view [the wip docs](https://docs-git-j0-addauthhttphookdocs-supabase.vercel.app/docs/guides/auth/auth-hooks?queryGroups=language&language=send-sms-json-schema) and [example README](examples/edge-functions/supabase/functions/send-sms/README.md) for details about HTTP Hooks. You can use [the JSON Schema Faker Tool](https://json-schema-faker.js.org/) in tandem with the Send SMS JSON Schema provided in order to generate a fake payload to test the function with.

Let us know if there's anything unclear or if there are any further questions or concerns. Thanks!

# Details About Contributing

## Contributing Format

We may feature some of the functions on our Edge Function Guides - if you wish for your regional sender to be considered, please paste a link to a Github repository containing a `README.md`, an `.env.local` file, and an `index.ts` file containing the function content. We will then check with the appropriate team to see whether it would fit into the guides. 

Here's the README outline:

# Your-edge-function-name
- What does this edge function do?
- When would I want to use it?

Example: 

Use this Hook with the **Send SMS** Extension Point to send a message with an [AppHash](https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string) via Twilio Programmable Messaging. The App Hash identifies a mobile application and is embedded it an SMS to allow an Android application to determine that the message was intended for the Application. In turn, this allows for the App to fetch specific information, such as OTP codes, to perform autofill so that the user does not have to exit the application to retrieve information from a message.

## Configuration

- What env vars do I need to add to .env.local?
- Where do I find these env vars?

Example:

Copy the following environment variables from [the Twilio Console](https://console.twilio.com/) into your `.env.local` file:

```bash
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_PHONE_NUMBER=""
```

## Testing
- Include an example cURL function with which we can test the edge function

## Any other points of note?
- As needed.

**Comment by mutumbakato** [comment]
Hey @J0. I noticed that the HTTP hooks UI has been merged—thank you for your efforts on this! However, I'm encountering an issue: I'm unable to connect the edge function to Authentication as a hook. It seems that the hooks currently only accept database functions. Is there anything specific I need to do to establish this connection to the Edge functions?

Thank you for your assistance.

**Comment by J0** [comment]
Hey @mutumbakato,

Apologies on the delayed reply - it's merged but currently behind a feature flag. Should be unflagged once [the docs]( https://github.com/supabase/supabase/pull/25880/files) go in

**Comment by mutumbakato** [comment]
Thanks for the update, I'll be waiting for the actual release.

**Comment by shaharyarrahmad** [comment]
@J0 
Any update on this?
Can see sms hook in UI, But not firing.
Any update would be helpful. 
Thank you.

**Comment by J0** [comment]
Hey @shaharyarrahmad,

Yup that is correct - it is behind a feature flag. We're done with the implementation for the most part but need to release  the docs and go through the implementation. I know it has taken quite a while but it is coming soon. 

Do check back mid Aug - in the meantime feel free to use the locally hosted version or let us know if there's a specific provider you'd like to see so we can look into examples or similar

**Comment by shaharyarrahmad** [comment]
Thank tou @J0 ..
looking forward to it.

**Comment by kangmingtay** [comment]
hi everyone, we've just released the "Send SMS" hook - you can check out the following links:
- [Blog post](https://supabase.com/blog/third-party-auth-mfa-phone-send-hooks#auth-hooks-for-sms-and-email)
- [Guide for implementing the SMS hook](https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook?queryGroups=language&language=http)

**Comment by mutumbakato** [comment]
Hey Kang, thanks a lot for shipping this, it's going to be very helpful. I've been trying it out and I realised that I still can't enable phone auth provider without selecting one of the listed phone providers. It there any other way I can do this?

**Comment by kangmingtay** [comment]
@mutumbakato thanks for raising this - i've made a fix for it here so it should work properly now (https://github.com/supabase/supabase/pull/28706)

**Comment by dileeshaupview** [comment]
Hey Guys, I'm trying to use "Send SMS" hook, on self-hosted supabase.
currently I added these to my docker-compose.yml and .env files as well
      GOTRUE_EXTERNAL_PHONE_ENABLED: true
      GOTRUE_HOOK_CUSTOM_SMS_PROVIDER_ENABLED: true
      GOTRUE_HOOK_CUSTOM_SMS_PROVIDER_URI: http://host.docker.internal:8000/functions/v1/send_sms
      GOTRUE_HOOK_CUSTOM_SMS_PROVIDER_SECRET: v1,whsec_9XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      
but gives me this error 
**AuthApiError: Unable to get SMS provider**

can you help me to figure out this.

**Comment by J0** [comment]
Hey @dileeshaupview,

Thanks for the update and detailed email. Surfacing this here so that others may learn as well. Can you share your .env or .toml file?


Specifically, wondering if you have `GOTRUE_SMS_PROVIDER="<provider>"` set and also what the version of the auth service you're running.

You can check the version by running `docker ps` . It should be contained in the image tag

**Comment by dileeshaupview** [comment]
Hi Joel,

Thanks for the feedback! Here's a quick update based on your suggestions:

1. I have now updated all Supabase images to the latest versions through docker-compose.yml, including the auth service, which was updated from supabase/gotrue:v2.151.0 to v2.158.1.

2. I wanted to clarify regarding the GOTRUE_SMS_PROVIDER="<provider>" setting, should I need to add this, and if so, what value should I be entering as the provider?

I'll continue testing and will report back on further progress.

Thanks again for your help!

**Comment by ssudaraka** [comment]
Hi @dileeshaupview ,

Can you try these configurations in your `docker-compose.yml` file?

```
GOTRUE_HOOK_SEND_SMS_ENABLED: "true"
GOTRUE_HOOK_SEND_SMS_URI: "http://host.docker.internal:8000/functions/v1/send-sms"
GOTRUE_HOOK_SEND_SMS_SECRETS: "v1,whsec_VGhpcyBpcyBhbiBleGFtcGxlIG9mIGEgc2hvcnRlciBCYXNlNjQgc3RyaW5n"
```

You won't be needing the `GOTRUE_SMS_PROVIDER` setting. Also, note that `true` must be wrapped with double quotations.

**Comment by dileeshaupview** [comment]
> Hi @dileeshaupview ,
> 
> Can you try these configurations in your `docker-compose.yml` file?
> 
> ```
> GOTRUE_HOOK_SEND_SMS_ENABLED: "true"
> GOTRUE_HOOK_SEND_SMS_URI: "http://host.docker.internal:8000/functions/v1/send-sms"
> GOTRUE_HOOK_SEND_SMS_SECRETS: "v1,whsec_VGhpcyBpcyBhbiBleGFtcGxlIG9mIGEgc2hvcnRlciBCYXNlNjQgc3RyaW5n"
> ```
> 
> You won't be needing the `GOTRUE_SMS_PROVIDER` setting. Also, note that `true` must be wrapped with double quotations.

Thank you so much for your help!  This is Working

**Comment by ankenu** [comment]
> Hi [@dileeshaupview](https://github.com/dileeshaupview) ,
> 
> Can you try these configurations in your `docker-compose.yml` file?
> 
> ```
> GOTRUE_HOOK_SEND_SMS_ENABLED: "true"
> GOTRUE_HOOK_SEND_SMS_URI: "http://host.docker.internal:8000/functions/v1/send-sms"
> GOTRUE_HOOK_SEND_SMS_SECRETS: "v1,whsec_VGhpcyBpcyBhbiBleGFtcGxlIG9mIGEgc2hvcnRlciBCYXNlNjQgc3RyaW5n"
> ```
> 
> You won't be needing the `GOTRUE_SMS_PROVIDER` setting. Also, note that `true` must be wrapped with double quotations.

Hi. I have the error "Failed to send magic link: Error unmarshaling Send SMS output" when I click to "Send OTP" button.

![Image](https://github.com/user-attachments/assets/11ca2bad-1a68-4bf5-b68f-c4f2733df9ad)

**Comment by ssudaraka** [comment]
@ankenu it's possible your hook is returning an error response (anything else other than status code 200). can you confirm the hook you configured is accessible and sending a successful response?

**Comment by ankenu** [comment]
> [@ankenu](https://github.com/ankenu) it's possible your hook is returning an error response (anything else other than status code 200). can you confirm the hook you configured is accessible and sending a successful response?

I'm getting an error with code 500, judging by the logs. This is what happens in the logs when the hook is called.
```
{"auth_event":{"action":"user_recovery_requested","actor_id":"9d1f4a5d-2054-4a65-8b52-abb6f0196db3","actor_username":"<my_phone>","actor_via_sso":false,"log_type":"user","traits":{"channel":"sms"}},"component":"api","duration":4893976860,"level":"info","method":"POST","msg":"request completed","path":"/otp","referer":"<my_supabase_host_url>","remote_addr":"10.0.2.7","request_id":"fb4be1b8-530a-47c0-bb22-d2a18d21a897","status":500,"time":"2025-01-24T15:13:18Z"}
```

**Comment by ankenu** [comment]
> [@ankenu](https://github.com/ankenu) it's possible your hook is returning an error response (anything else other than status code 200). can you confirm the hook you configured is accessible and sending a successful response?

Thank you for your answer. You were right. The error was that the function returned an empty object. There is an error on line 78 in the [documentation](https://supabase.com/docs/guides/auth/auth-hooks/send-sms-hook?queryGroups=language&language=http).

**Comment by ianSurii** [comment]
Africa's Talking hook : [https://github.com/ianSurii/supabase-africas-talking-sms](url)
Covers sandbox + production, signature verification, and East/West African number formats (+254, +234, +256, +255, +233, +250).
