### ISSUE TITLE
Failed to validate template: content must be shorter than or equal to 5000 characters" despite template being under character limit

### ISSUE THREAD

**Issue by nicokempe** [supabase/auth#1835]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Supabase returns an error "Failed to validate template: content must be shorter than or equal to 5000 characters," although the email template I am using does not exceed this limit. The template is about 3700 characters, and even when minified, it reaches only 2088 characters. This issue appears to be a false positive on the character limit validation.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create an email template with approximately 3700 characters.
2. Minify the template to reduce character count.
3. Attempt to save or use the template within Supabase.
4. Observe the error stating the content exceeds 5000 characters.
5. I have added one of my email templates to reproduce the issue

## Expected behavior

The template should save successfully without triggering the character limit validation error, as it does not exceed the 5000-character limit. It worked already for the last months but it just stopped working, the last email I got has been received 2 days ago.

## Screenshots

Network Traffic (comes from spam protection?)
![image](https://github.com/user-attachments/assets/f8da89f8-ac42-49c5-ad86-a94c792cb955)

Error notification when navigating to another email template:
![image](https://github.com/user-attachments/assets/59a64792-ae77-435e-b4a0-bbb131476a34)

## System information

* Website: [Supabase Cloud](https://supabase.com/dashboard/project/qyjgjvclovhpvynbofdd/auth/templates)
* Plan: Free
* Organization: "Dashio KG" (qyjgjvclovhpvynbofdd)
* Browser: Tested on both, Microsoft Edge and Mozilla Firefox

## Additional context

This issue occurs even after minifying the template. The problem suggests that the character count validation may not be accurately calculated on Supabase's end, potentially counting whitespace or other formatting redundantly. The error is new, as similar templates with similar character counts previously saved without issues.

One of my used email templates is attached. Thanks for your support!

[minified-custom-email-template-magic-link.zip](https://github.com/user-attachments/files/17703986/minified-custom-email-template-magic-link.zip)

**Comment by nicokempe** [comment]
After further investigation, including both front-end and backend code analysis within the Supabase codebase, no configurations or validation constants defining a 5000-character limit have been identified.  This suggests the character limit may be enforced at a deeper level within Supabase's backend infrastructure or as a recent change not reflected in the public codebase.

Thank you for your assistance, and please let me know if further testing or details would be useful!

**Comment by phamhieu** [comment]
Hi @nicokempe, thanks for the report! We'll be increasing the max content length for the template validation api. This limit is in place to protect our api service. 
Rest assured, there's no limit on the template length, so this error won't prevent you from saving the template.

**Comment by cstockton** [comment]
This issue should be resolved, please let me know if it isn't.

**Comment by nicokempe** [comment]
Yes it does works now, thank you guys very much!

**Comment by meridian-auctions** [comment]
Hey guys. I still have an issue here I'm hitting the 50,000 character limit when using custom html template from Klaviyo to match the theming and style of all of our other emails.

![Image](https://github.com/user-attachments/assets/17a5d506-d8f9-43d9-83a8-52e91c8fa8fd)

I'm building an 'invite user' flow and its crucial the email contains thorough onboarding information as the application were building is for a closed network I.e. invite only - from artists who have applied to join the platform.

I'm happy to sacrifice the built in Supabase Emails if there's clear guidance on how I can replace this with my own via Resend directly or something, but its not clear how to use the Supabase invite user flow and not use the built in emails...

Please help
